server:
  port: 9400

spring:
  application:
    name: auth-center
#  jpa:
#    show-sql: true
  datasource:
    url: jdbc:mysql://121.40.204.36/rspsdb?useUnicode=true&characterEncoding=utf-8 # jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: rspsadmin # root
    password: rsps!@#zhuixin # 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  zipkin:
      base-url: http://localhost:9300
  sleuth:
    sampler:
      percentage: 1.0
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3

