eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
server:
  port: 10500
spring:
  application:
    name: location-service
  cloud:
    stream:
      bindings:
        input_basestation:
          group: location-service
          destination: basestation
          consumer:
            concurrency: 10
        input_operlocation:
          group: location-service
          destination: operlocation
  rabbitmq:
    host: 192.168.0.111
    port: 5672
    username: izhuixin
    password: rsps123456
  zipkin:
    base-url: http://localhost:9300
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    url: jdbc:mysql://192.168.0.111/base_station?charset=utf8
    username: rspsadmin
    password: rsps!@#Test
    #rsps!@#Test
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com.izhuixin.rsps.mapping/*.xml
  type-aliases-package: com.izhuixin.rsps.model.CoapModel.*
endpoints.shutdown.enabled: true    #开启优雅关闭方式
management.security.enabled: false  #关闭安全认证



