eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
server:
  port: 10600
spring:
  application:
    name: coap-service
  zipkin:
    base-url: http://localhost:9300
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    host: 121.40.204.36
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  cloud:
     stream:
       bindings:
         output_basestation:
           destination: basestation
         output_boxdata:
           destination: coap_boxdata
  rabbitmq:
     host: 121.40.204.36
     port: 5672
     username: izhuixin
     password: rsps123456
mybatis:
  mapper-locations: classpath:com.izhuixin.rsps.mapping/*.xml
  type-aliases-package: com.izhuixin.rsps.model.*
endpoints.shutdown.enabled: true    #开启优雅关闭方式
management.security.enabled: false  #关闭安全认证
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000




