eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
server:
  port: 9100
spring:
  application:
    name: registry-center