spring:
  application:
    name: gate-way
  zipkin:
    base-url: http://localhost:9300
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    host: 192.168.0.111
    port: 6379
    database: 0
    password:
    timeout: 0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  session:
    store-type: redis
server:
  port: 9200
eureka:
  client:
      service-url:
        defaultZone: http://localhost:9100/eureka/
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####

###如下Oauth2.0配置参考##
###https://stackoverflow.com/questions/30327269/spring-oauth-authorization-server-behind-spring-cloud-zuul-proxy##
###https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc##
###http://wiselyman.iteye.com/blog/2379419##
#######
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    uaa:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: auth-center
    api-a:
      path: /api/**
      serviceId: api-service
    api-b:
      path: /manager/**
      sensitiveHeaders:
      serviceId: manage-service
    api-c:
      path: /custom/**
      sensitiveHeaders:
      serviceId: wechat-service
    api-assets:
      path: /assets/**
      sensitiveHeaders:
      serviceId: assets-service
security:
  basic:
      enabled: false
  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: webApp # f6b0c47fe639f31689fb
      clientSecret: webApp # 39b7dd1dc8fb3f409edea6d9e096a3c5ee30ed4e
      accessTokenUri: http://localhost:9200/uaa/oauth/token # https://github.com/login/oauth/access_token
      userAuthorizationUri: http://localhost:9200/uaa/oauth/authorize # https://github.com/login/oauth/authorize
    resource:
      userInfoUri: http://localhost:9400/user # https://api.github.com/user
      preferTokenInfo: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 180000
###超时配置###